#!/bin/bash

inotifywait -e close_write,moved_to,create -mr . |
while read -r directory events filename; do
  if [[ "$filename" =~ \.cs$ ]]; then
    echo ""
    echo "Parsing $directory$filename"
    mcs --parse "$directory$filename"
    echo "~Fin"
  elif [[ "$filename" =~ \.txt$ ]]; then
    echo ""
    echo "════════════Output═════════════"
    cat "$directory$filename"
    echo "═══════════════════════════════"
  fi
done
